# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: This checkout clone the github repository on the machine
      uses: actions/checkout@v4
    - name: Use Node.js v18.19.1
      uses: actions/setup-node@v4
      with:
        node-version: 18.19.1
        cache: 'npm'
    - name: Install programm dependencies
      run: npm install
    - name: Start the app -> & makes the process background mode
      run: npm run start &
    - name: Run integration tests
      run: npm run test
